import {
  StudentProfile,
  SubjectAttendance,
  InternalMark,
  SemesterResult,
  TimetableSlot,
  Assignment,
  CollegeNotice,
  LeaveRequest,
  StudyPlan,
  CampusBuilding,
  CampusRoom,
  CampusLab,
  AchievementBadge,
  ParentFeeInfo,
} from './types';

export const INITIAL_STUDENT_PROFILE: StudentProfile = {
  id: 'std_089',
  name: 'Alex Rivera',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  email: 'alex.rivera@campus.edu',
  department: 'Computer Science & Engineering',
  year: '3rd Year (Class of 2027)',
  semester: 6,
  rollNumber: 'CS2024-089',
  section: 'CSE-B',
  bloodGroup: 'O+ve',
  advisor: 'Dr. Sarah Mitchell',
  parentName: 'Robert Rivera',
  parentPhone: '+1 (555) 382-9912',
};

export const INITIAL_ATTENDANCE: SubjectAttendance[] = [
  {
    id: 'att_1',
    code: 'CS301',
    name: 'Database Management Systems',
    faculty: 'Prof. David Chen',
    attended: 37,
    total: 42,
    percentage: 88.1,
    minimumRequired: 75,
    status: 'safe',
  },
  {
    id: 'att_2',
    code: 'CS302',
    name: 'Operating Systems & Networks',
    faculty: 'Dr. Sarah Mitchell',
    attended: 31,
    total: 40,
    percentage: 77.5,
    minimumRequired: 75,
    status: 'safe',
  },
  {
    id: 'att_3',
    code: 'CS303',
    name: 'Design & Analysis of Algorithms',
    faculty: 'Prof. Marcus Vance',
    attended: 27,
    total: 38,
    percentage: 71.0,
    minimumRequired: 75,
    status: 'warning',
  },
  {
    id: 'att_4',
    code: 'CS304',
    name: 'Machine Learning & AI Systems',
    faculty: 'Dr. Elena Rostova',
    attended: 41,
    total: 44,
    percentage: 93.2,
    minimumRequired: 75,
    status: 'safe',
  },
  {
    id: 'att_5',
    code: 'CS305',
    name: 'Cloud & Full-Stack Web Eng.',
    faculty: 'Prof. Jason Kim',
    attended: 33,
    total: 39,
    percentage: 84.6,
    minimumRequired: 75,
    status: 'safe',
  },
];

export const INITIAL_INTERNAL_MARKS: InternalMark[] = [
  {
    id: 'im_1',
    subjectCode: 'CS301',
    subjectName: 'Database Management Systems',
    assessment1: 18,
    assessment2: 17,
    assignmentMarks: 9,
    total: 44,
    maxTotal: 50,
    classAverage: 38.5,
    grade: 'A+',
  },
  {
    id: 'im_2',
    subjectCode: 'CS302',
    subjectName: 'Operating Systems & Networks',
    assessment1: 16,
    assessment2: 15,
    assignmentMarks: 8,
    total: 39,
    maxTotal: 50,
    classAverage: 36.0,
    grade: 'A',
  },
  {
    id: 'im_3',
    subjectCode: 'CS303',
    subjectName: 'Design & Analysis of Algorithms',
    assessment1: 14,
    assessment2: 13,
    assignmentMarks: 7,
    total: 34,
    maxTotal: 50,
    classAverage: 35.2,
    grade: 'B+',
  },
  {
    id: 'im_4',
    subjectCode: 'CS304',
    subjectName: 'Machine Learning & AI Systems',
    assessment1: 19,
    assessment2: 20,
    assignmentMarks: 10,
    total: 49,
    maxTotal: 50,
    classAverage: 40.1,
    grade: 'O (Outstanding)',
  },
  {
    id: 'im_5',
    subjectCode: 'CS305',
    subjectName: 'Cloud & Full-Stack Web Eng.',
    assessment1: 17,
    assessment2: 18,
    assignmentMarks: 9,
    total: 44,
    maxTotal: 50,
    classAverage: 39.0,
    grade: 'A+',
  },
];

export const SEMESTER_RESULTS: SemesterResult[] = [
  {
    semester: 5,
    gpa: 8.52,
    creditsEarned: 22,
    totalCredits: 22,
    status: 'Distinction',
    subjects: [
      { code: 'CS501', name: 'Software Architecture', grade: 'A+', gradePoint: 9, credits: 4 },
      { code: 'CS502', name: 'Computer Graphics', grade: 'A', gradePoint: 8, credits: 3 },
      { code: 'CS503', name: 'Distributed Databases', grade: 'O', gradePoint: 10, credits: 4 },
      { code: 'CS504', name: 'Compiler Engineering', grade: 'B+', gradePoint: 7, credits: 4 },
      { code: 'CS505', name: 'IoT Sensor Networks', grade: 'A+', gradePoint: 9, credits: 4 },
      { code: 'CS506', name: 'Systems Engineering Lab', grade: 'O', gradePoint: 10, credits: 3 },
    ],
  },
  {
    semester: 4,
    gpa: 8.35,
    creditsEarned: 24,
    totalCredits: 24,
    status: 'Passed',
    subjects: [
      { code: 'CS401', name: 'Theory of Computation', grade: 'A', gradePoint: 8, credits: 4 },
      { code: 'CS402', name: 'Microprocessors & Microcontrollers', grade: 'B+', gradePoint: 7, credits: 4 },
      { code: 'CS403', name: 'Object Oriented Programming', grade: 'O', gradePoint: 10, credits: 4 },
      { code: 'CS404', name: 'Discrete Mathematics', grade: 'A+', gradePoint: 9, credits: 4 },
      { code: 'CS405', name: 'Cybersecurity Fundamentals', grade: 'A', gradePoint: 8, credits: 4 },
      { code: 'CS406', name: 'Hardware Simulation Lab', grade: 'A+', gradePoint: 9, credits: 4 },
    ],
  },
  {
    semester: 3,
    gpa: 8.40,
    creditsEarned: 23,
    totalCredits: 23,
    status: 'Passed',
    subjects: [
      { code: 'CS301', name: 'Data Structures with C++', grade: 'A+', gradePoint: 9, credits: 4 },
      { code: 'CS302', name: 'Digital Logic Circuits', grade: 'A', gradePoint: 8, credits: 4 },
      { code: 'CS303', name: 'Engineering Mathematics III', grade: 'B+', gradePoint: 7, credits: 4 },
      { code: 'CS304', name: 'Principles of Programming Languages', grade: 'A+', gradePoint: 9, credits: 4 },
      { code: 'CS305', name: 'Professional Ethics in Computing', grade: 'O', gradePoint: 10, credits: 3 },
      { code: 'CS306', name: 'Data Structures Lab', grade: 'O', gradePoint: 10, credits: 4 },
    ],
  },
];

export const TODAY_TIMETABLE: TimetableSlot[] = [
  {
    id: 'tt_1',
    day: 'Thursday',
    startTime: '08:30 AM',
    endTime: '09:30 AM',
    subjectCode: 'CS303',
    subjectName: 'Design & Analysis of Algorithms',
    facultyName: 'Prof. Marcus Vance',
    roomNumber: 'LH-302 (Tech Block A)',
    type: 'Lecture',
    isCurrent: false,
  },
  {
    id: 'tt_2',
    day: 'Thursday',
    startTime: '09:45 AM',
    endTime: '11:15 AM',
    subjectCode: 'CS304',
    subjectName: 'Machine Learning & AI Systems',
    facultyName: 'Dr. Elena Rostova',
    roomNumber: 'AI Lab 3 (Computing Wing)',
    type: 'Lab',
    isCurrent: true,
  },
  {
    id: 'tt_3',
    day: 'Thursday',
    startTime: '11:30 AM',
    endTime: '12:30 PM',
    subjectCode: 'CS301',
    subjectName: 'Database Management Systems',
    facultyName: 'Prof. David Chen',
    roomNumber: 'LH-104 (Tech Block A)',
    type: 'Lecture',
    isCurrent: false,
  },
  {
    id: 'tt_4',
    day: 'Thursday',
    startTime: '01:30 PM',
    endTime: '03:30 PM',
    subjectCode: 'CS305',
    subjectName: 'Cloud & Full-Stack Web Eng. Workshop',
    facultyName: 'Prof. Jason Kim',
    roomNumber: 'Innovation Studio (Ground Floor)',
    type: 'Tutorial',
    isCurrent: false,
  },
  {
    id: 'tt_5',
    day: 'Thursday',
    startTime: '03:45 PM',
    endTime: '04:45 PM',
    subjectCode: 'CS302',
    subjectName: 'Operating Systems & Networks',
    facultyName: 'Dr. Sarah Mitchell',
    roomNumber: 'LH-201 (Science Block)',
    type: 'Lecture',
    isCurrent: false,
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg_1',
    title: 'B-Tree & Query Optimizer Execution Plan Analysis',
    subjectCode: 'CS301',
    subjectName: 'Database Management Systems',
    facultyName: 'Prof. David Chen',
    dueDate: 'Tomorrow, 11:59 PM',
    priority: 'High',
    status: 'Due Soon',
    description: 'Provide query execution plans comparing nested-loop vs hash joins on a 1M record table dataset.',
    attachmentName: 'dbms_assignment_3_specs.pdf',
  },
  {
    id: 'asg_2',
    title: 'Dynamic Programming vs Branch & Bound Benchmark',
    subjectCode: 'CS303',
    subjectName: 'Design & Analysis of Algorithms',
    facultyName: 'Prof. Marcus Vance',
    dueDate: 'Sep 13, 2026',
    priority: 'High',
    status: 'Upcoming',
    description: 'Implement 0/1 Knapsack solution with time complexity profiling graphs across varying constraints.',
    attachmentName: 'knapsack_benchmark_code_template.zip',
  },
  {
    id: 'asg_3',
    title: 'Linux Kernel Process Scheduling Simulation',
    subjectCode: 'CS302',
    subjectName: 'Operating Systems & Networks',
    facultyName: 'Dr. Sarah Mitchell',
    dueDate: 'Yesterday, 05:00 PM',
    priority: 'Medium',
    status: 'Overdue',
    description: 'Simulate Completely Fair Scheduler (CFS) with red-black tree logic and latency comparison.',
    attachmentName: 'cfs_scheduler_report.pdf',
  },
  {
    id: 'asg_4',
    title: 'Convolutional Neural Network for Medical Imaging',
    subjectCode: 'CS304',
    subjectName: 'Machine Learning & AI Systems',
    facultyName: 'Dr. Elena Rostova',
    dueDate: 'Sep 05, 2026',
    priority: 'High',
    status: 'Submitted',
    submittedAt: 'Sep 04, 2026 - 10:24 PM',
    marksAwarded: '19.5 / 20',
    description: 'ResNet-50 transfer learning pipeline with confusion matrix and 94.2% test accuracy report.',
    attachmentName: 'alex_rivera_resnet50_final.ipynb',
  },
  {
    id: 'asg_5',
    title: 'Microservices Deployment on Kubernetes Cluster',
    subjectCode: 'CS305',
    subjectName: 'Cloud & Full-Stack Web Eng.',
    facultyName: 'Prof. Jason Kim',
    dueDate: 'Sep 18, 2026',
    priority: 'Medium',
    status: 'Upcoming',
    description: 'Deploy 3 tiered containerized services with Ingress routing, horizontal pod autoscaling, and Helm chart.',
  },
];

export const INITIAL_NOTICES: CollegeNotice[] = [
  {
    id: 'not_1',
    title: 'Mid-Semester Examinations Schedule & Mandatory Hall Ticket Guidelines',
    category: 'Exam',
    priority: 'Critical',
    date: 'Sep 09, 2026',
    author: 'Controller of Examinations',
    read: false,
    content: 'The Mid-Semester Examination for all Year 3 Engineering students commences on September 22, 2026. Hall tickets will be downloadable via the student portal starting September 15. Students with attendance under 75% will need department head condonation approval. Carrying smart watches or programmable calculators into exam halls is strictly prohibited.',
    aiSummary: {
      what: 'Mid-Semester Exam schedule release and hall ticket distribution instructions.',
      when: 'Exams begin Sep 22, 2026. Hall tickets available starting Sep 15.',
      where: 'Exam Halls (Main Examination Complex, Floors 2 & 3).',
      who: 'All 3rd Year B.Tech Engineering Students.',
      action: 'Check attendance > 75%, download hall ticket on Sep 15, leave smart gadgets at home.',
    },
  },
  {
    id: 'not_2',
    title: 'Annual Tech Hackathon 2026: Registrations Open & Cash Prizes Announced',
    category: 'Event',
    priority: 'Important',
    date: 'Sep 08, 2026',
    author: 'Innovation & Incubation Cell',
    read: false,
    content: 'Registrations are officially open for "HackNova 2026", our 36-hour campus hackathon scheduled for October 4-5. Tracks include AI & Healthcare, CleanTech, Smart Cities, and Autonomous Systems. Total prize pool is $15,000 with incubation opportunities from partner venture funds. Teams of 2-4 students can register through the portal.',
    aiSummary: {
      what: 'HackNova 2026 - 36-Hour National Level College Hackathon.',
      when: 'October 4 - 5, 2026 (Registration closes Sep 25).',
      where: 'Auditorium & Innovation Labs, Tech Block.',
      who: 'Undergraduate and postgraduate students in teams of 2 to 4.',
      action: 'Form your team of 2-4 and submit project abstract before Sep 25.',
    },
  },
  {
    id: 'not_3',
    title: 'Department Seminar on LLM Fine-Tuning & Multi-Agent Systems by Google DeepMind',
    category: 'Department',
    priority: 'Important',
    date: 'Sep 07, 2026',
    author: 'CSE Department Board',
    read: true,
    content: 'The CSE Department is thrilled to host Dr. Amanda Vance, Senior Staff Research Scientist at Google DeepMind, for an interactive seminar titled "Architecting Production-Grade Multi-Agent Systems with Gemini" this Friday from 2:00 PM to 4:00 PM at Seminar Hall A. Attendance counts towards CS304 laboratory credits.',
    aiSummary: {
      what: 'Special technical guest lecture on Multi-Agent Systems with Gemini.',
      when: 'Friday, 2:00 PM – 4:00 PM.',
      where: 'Seminar Hall A, Science Wing.',
      who: 'CSE & AI branch students (counts toward CS304 lab credit).',
      action: 'Arrive 10 minutes prior to 2:00 PM with your student ID badge.',
    },
  },
  {
    id: 'not_4',
    title: 'Campus Central Server Maintenance Window & Temporary Portal Interruption',
    category: 'Administrative',
    priority: 'General',
    date: 'Sep 05, 2026',
    author: 'Campus IT Infrastructure Services',
    read: true,
    content: 'Please be advised that the central campus proxy, printing queues, and internal file servers will undergo routine kernel security updates on Saturday, September 12 from 01:00 AM to 04:00 AM. Cloud-based Smart College Assistant endpoints will remain online with uninterrupted availability.',
    aiSummary: {
      what: 'Routine IT network server patching and brief local infrastructure downtime.',
      when: 'Saturday, Sep 12 (01:00 AM – 04:00 AM).',
      where: 'Campus local area network & physical lab workstations.',
      who: 'All campus occupants using local campus intranet.',
      action: 'No action required; cloud portals remain accessible.',
    },
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr_1',
    studentId: 'std_089',
    studentName: 'Alex Rivera',
    rollNumber: 'CS2024-089',
    leaveType: 'Academic Event',
    startDate: '2026-09-15',
    endDate: '2026-09-16',
    totalDays: 2,
    reason: 'Presenting research paper on LLM Agent orchestration at the Regional Student AI Symposium.',
    documentName: 'symposium_invitation_letter.pdf',
    status: 'Pending',
    appliedDate: '2026-09-09',
    facultyReviewer: 'Dr. Sarah Mitchell',
  },
  {
    id: 'lr_2',
    studentId: 'std_089',
    studentName: 'Alex Rivera',
    rollNumber: 'CS2024-089',
    leaveType: 'Medical',
    startDate: '2026-08-20',
    endDate: '2026-08-21',
    totalDays: 2,
    reason: 'Severe viral flu with doctor recommendation for bed rest.',
    documentName: 'medical_prescription_clinic.pdf',
    status: 'Approved',
    appliedDate: '2026-08-19',
    remarks: 'Approved with medical certificate verified by campus medical officer.',
    facultyReviewer: 'Dr. Sarah Mitchell',
  },
];

export const INITIAL_STUDY_PLAN: StudyPlan = {
  id: 'sp_1',
  generatedDate: 'Today, 07:00 AM',
  targetExam: 'Mid-Term Examinations',
  examCountdownDays: 12,
  availableHours: 4.5,
  tasks: [
    {
      id: 'st_1',
      timeSlot: '07:30 AM - 08:30 AM',
      subject: 'Algorithms (CS303)',
      topic: 'Dynamic Programming & Memoization Patterns',
      durationMinutes: 60,
      priority: 'High',
      completed: true,
    },
    {
      id: 'st_2',
      timeSlot: '05:00 PM - 06:00 PM',
      subject: 'Database Systems (CS301)',
      topic: 'Transaction ACID Properties & Two-Phase Locking',
      durationMinutes: 60,
      priority: 'High',
      completed: false,
    },
    {
      id: 'st_3',
      timeSlot: '06:15 PM - 07:15 PM',
      subject: 'Operating Systems (CS302)',
      topic: 'Virtual Memory, Page Replacement & TLB Cache',
      durationMinutes: 60,
      priority: 'Medium',
      completed: false,
    },
    {
      id: 'st_4',
      timeSlot: '08:00 PM - 08:45 PM',
      subject: 'Machine Learning (CS304)',
      topic: 'Review Gradient Descent & Backpropagation equations',
      durationMinutes: 45,
      priority: 'Low',
      completed: false,
    },
    {
      id: 'st_5',
      timeSlot: '09:00 PM - 09:30 PM',
      subject: 'Assignment Work',
      topic: 'Complete DBMS execution plan queries and documentation',
      durationMinutes: 30,
      priority: 'High',
      completed: false,
    },
  ],
};

export const CAMPUS_BUILDINGS: CampusBuilding[] = [
  {
    id: 'bld_1',
    name: 'Tech Block A (Alan Turing Complex)',
    code: 'TBA',
    description: 'Primary Engineering lectures, department offices, and faculty chambers.',
    floors: 5,
    facilities: ['Lecture Halls 101-504', 'Department Library', 'Faculty Lounges', 'Water Filtration Stations'],
    coordinates: { x: 28, y: 35 },
  },
  {
    id: 'bld_2',
    name: 'Computing & AI Complex',
    code: 'CAC',
    description: 'State-of-the-art computer labs, GPU research clusters, and data centers.',
    floors: 4,
    facilities: ['AI Lab 1-4', 'Cyber Security Center', 'Cloud Computing Hub', 'Hardware IoT Lab'],
    coordinates: { x: 55, y: 30 },
  },
  {
    id: 'bld_3',
    name: 'Science & Innovation Wing',
    code: 'SIW',
    description: 'Applied physics, mathematics, chemistry labs, and incubator rooms.',
    floors: 3,
    facilities: ['Seminar Hall A & B', 'Maker Space', 'Robotics Arena', 'Incubation Office'],
    coordinates: { x: 75, y: 55 },
  },
  {
    id: 'bld_4',
    name: 'Central Library & Learning Hub',
    code: 'CLL',
    description: '24/7 digital resource center, silent study pods, and thesis archives.',
    floors: 4,
    facilities: ['Digital Media Center', 'Discussion Rooms 1-12', 'Café Reading Terrace', 'Periodicals Wing'],
    coordinates: { x: 38, y: 68 },
  },
  {
    id: 'bld_5',
    name: 'Administrative Tower & Dean Office',
    code: 'ADM',
    description: 'Admissions, examinations controller, accounts, and student affairs.',
    floors: 4,
    facilities: ['Controller of Exams', 'Accounts & Fees Desk', 'Registrar Office', 'Auditorium'],
    coordinates: { x: 18, y: 75 },
  },
  {
    id: 'bld_6',
    name: 'Student Center & Food Court',
    code: 'SFC',
    description: 'Multi-cuisine food court, recreation zone, and student council hall.',
    floors: 2,
    facilities: ['Food Court', 'Campus Bookstore', 'Health Clinic', 'ATM Center'],
    coordinates: { x: 62, y: 78 },
  },
];

export const CAMPUS_ROOMS: CampusRoom[] = [
  {
    id: 'rm_101',
    roomNumber: 'LH-101',
    building: 'Tech Block A (Alan Turing Complex)',
    floor: 1,
    type: 'Classroom',
    capacity: 65,
    isAvailable: true,
    nextAvailableTime: 'Open until 02:00 PM',
  },
  {
    id: 'rm_104',
    roomNumber: 'LH-104',
    building: 'Tech Block A (Alan Turing Complex)',
    floor: 1,
    type: 'Classroom',
    capacity: 70,
    isAvailable: false,
    currentActivity: 'CS301 Lecture (Prof. David Chen)',
    nextAvailableTime: '12:30 PM',
  },
  {
    id: 'rm_202',
    roomNumber: 'LH-202',
    building: 'Tech Block A (Alan Turing Complex)',
    floor: 2,
    type: 'Classroom',
    capacity: 60,
    isAvailable: true,
    nextAvailableTime: 'Available all day',
  },
  {
    id: 'rm_302',
    roomNumber: 'LH-302',
    building: 'Tech Block A (Alan Turing Complex)',
    floor: 3,
    type: 'Classroom',
    capacity: 80,
    isAvailable: true,
    nextAvailableTime: 'Open until 03:30 PM',
  },
  {
    id: 'rm_sh_a',
    roomNumber: 'Seminar Hall A',
    building: 'Science & Innovation Wing',
    floor: 1,
    type: 'Seminar Hall',
    capacity: 220,
    isAvailable: false,
    currentActivity: 'Industry Tech Keynote Setup',
    nextAvailableTime: '04:30 PM',
  },
  {
    id: 'rm_sh_b',
    roomNumber: 'Seminar Hall B',
    building: 'Science & Innovation Wing',
    floor: 2,
    type: 'Seminar Hall',
    capacity: 150,
    isAvailable: true,
    nextAvailableTime: 'Available until 05:00 PM',
  },
  {
    id: 'rm_lib_pod',
    roomNumber: 'Study Pod 04',
    building: 'Central Library & Learning Hub',
    floor: 2,
    type: 'Classroom',
    capacity: 8,
    isAvailable: true,
    nextAvailableTime: 'Available for reservation',
  },
];

export const CAMPUS_LABS: CampusLab[] = [
  {
    id: 'lab_1',
    name: 'Advanced AI & Deep Learning Lab',
    code: 'AI-LAB-3',
    building: 'Computing & AI Complex',
    floor: 2,
    totalSystems: 45,
    availableSystems: 14,
    status: 'Available',
    inCharge: 'Dr. Elena Rostova',
    nextSlot: 'Class reserved at 02:00 PM',
  },
  {
    id: 'lab_2',
    name: 'Cloud Virtualization & Distributed Systems Lab',
    code: 'CLOUD-LAB-1',
    building: 'Computing & AI Complex',
    floor: 3,
    totalSystems: 50,
    availableSystems: 0,
    status: 'Occupied',
    inCharge: 'Prof. Jason Kim',
    nextSlot: 'Freed up at 01:15 PM',
  },
  {
    id: 'lab_3',
    name: 'Network Security & Penetration Testing Lab',
    code: 'SEC-LAB-2',
    building: 'Computing & AI Complex',
    floor: 1,
    totalSystems: 40,
    availableSystems: 28,
    status: 'Available',
    inCharge: 'Dr. Sarah Mitchell',
    nextSlot: 'Open access till 06:00 PM',
  },
  {
    id: 'lab_4',
    name: 'Embedded Systems & IoT Hardware Workshop',
    code: 'IOT-LAB-4',
    building: 'Science & Innovation Wing',
    floor: 1,
    totalSystems: 35,
    availableSystems: 22,
    status: 'Available',
    inCharge: 'Prof. Marcus Vance',
    nextSlot: 'Walk-in work allowed',
  },
];

export const ACHIEVEMENT_BADGES: AchievementBadge[] = [
  {
    id: 'ach_1',
    title: 'Consistency Star',
    description: 'Submitted 10 consecutive assignments before the deadline.',
    icon: 'Star',
    unlocked: true,
    unlockedDate: 'Sep 02, 2026',
    progressPercentage: 100,
    category: 'Assignments',
  },
  {
    id: 'ach_2',
    title: 'Study Streak Master',
    description: 'Completed scheduled study planner tasks for 7 days straight.',
    icon: 'Flame',
    unlocked: true,
    unlockedDate: 'Sep 08, 2026',
    progressPercentage: 100,
    category: 'Study',
  },
  {
    id: 'ach_3',
    title: 'Attendance Shield',
    description: 'Maintained above 85% attendance across all 5 core subjects.',
    icon: 'ShieldCheck',
    unlocked: false,
    progressPercentage: 78,
    category: 'Attendance',
  },
  {
    id: 'ach_4',
    title: 'Goal Achiever',
    description: 'Exceeded predicted semester GPA target in previous term.',
    icon: 'Target',
    unlocked: true,
    unlockedDate: 'Aug 14, 2026',
    progressPercentage: 100,
    category: 'Exams',
  },
  {
    id: 'ach_5',
    title: 'Campus Navigator',
    description: 'Used empty classroom locator & reserved 5 study sessions.',
    icon: 'Compass',
    unlocked: false,
    progressPercentage: 60,
    category: 'Study',
  },
];

export const PARENT_FEE_DATA: ParentFeeInfo = {
  totalFee: 8500,
  paidAmount: 6500,
  remainingAmount: 2000,
  dueDate: 'October 15, 2026',
  receiptNumber: 'REC-2026-FEE-88190',
  paymentHistory: [
    {
      id: 'pay_1',
      term: 'Semester 6 Tuition Installment 1',
      amount: 4000,
      date: 'July 10, 2026',
      status: 'Paid',
      method: 'Online Banking (REF: TXN88291)',
    },
    {
      id: 'pay_2',
      term: 'Annual Laboratory & Computing Infrastructure Fee',
      amount: 2500,
      date: 'July 10, 2026',
      status: 'Paid',
      method: 'Online Card (REF: TXN88292)',
    },
    {
      id: 'pay_3',
      term: 'Semester 6 Tuition Installment 2 (Final Balance)',
      amount: 2000,
      date: 'Due Oct 15, 2026',
      status: 'Pending',
      method: 'Pending Authorization',
    },
  ],
};

// Faculty class overview mock data
export const FACULTY_CLASS_STUDENTS = [
  { id: 's1', roll: 'CS2024-089', name: 'Alex Rivera', attendance: 78, internalMarks: 41, status: 'safe', risk: 'Low Risk' },
  { id: 's2', roll: 'CS2024-090', name: 'Jordan Hayes', attendance: 68, internalMarks: 29, status: 'warning', risk: 'At Risk (Attendance < 75%)' },
  { id: 's3', roll: 'CS2024-091', name: 'Maya Lin', attendance: 92, internalMarks: 48, status: 'safe', risk: 'Low Risk' },
  { id: 's4', roll: 'CS2024-092', name: 'Carlos Mendez', attendance: 64, internalMarks: 27, status: 'critical', risk: 'High Risk (Academic & Att.)' },
  { id: 's5', roll: 'CS2024-093', name: 'Priya Sharma', attendance: 86, internalMarks: 45, status: 'safe', risk: 'Low Risk' },
  { id: 's6', roll: 'CS2024-094', name: 'Liam O’Connor', attendance: 74, internalMarks: 33, status: 'warning', risk: 'Moderate Risk' },
];

export const ACHIEVEMENTS = [
  {
    id: 'ach_1',
    title: '15-Day Attendance Streak',
    description: 'Attended all scheduled lectures and labs for 15 consecutive days.',
    icon: '🔥',
    unlocked: true,
    unlockedDate: 'Sep 02, 2026',
    category: 'Attendance',
  },
  {
    id: 'ach_2',
    title: 'Early Bird Submitter',
    description: 'Turned in 3 consecutive assignments at least 24 hours before deadline.',
    icon: '⚡',
    unlocked: true,
    unlockedDate: 'Sep 08, 2026',
    category: 'Assignments',
  },
  {
    id: 'ach_3',
    title: 'Code Wizard (Algorithms)',
    description: 'Scored full marks on Dynamic Programming and Graph Theory assessments.',
    icon: '🧙‍♂️',
    unlocked: true,
    unlockedDate: 'Aug 28, 2026',
    category: 'Academics',
  },
  {
    id: 'ach_4',
    title: 'Focus Master (Pomodoro)',
    description: 'Completed 20 deep study sessions in Focus Mode without interruptions.',
    icon: '🎯',
    unlocked: false,
    category: 'Study',
  },
  {
    id: 'ach_5',
    title: 'Digital Scholar (8.5+ CGPA)',
    description: 'Maintained semester GPA strictly above 8.5 for two consecutive semesters.',
    icon: '🏆',
    unlocked: true,
    unlockedDate: 'Jun 20, 2026',
    category: 'Exams',
  },
  {
    id: 'ach_6',
    title: 'Campus Navigator',
    description: 'Booked 5 empty classrooms for peer group study sessions.',
    icon: '🧭',
    unlocked: false,
    category: 'Campus',
  },
];

export const LEADERBOARD = [
  { rank: 1, name: 'Maya Lin', rollNumber: 'CS2024-091', points: 1820, attendance: 96, badge: 'Grandmaster' },
  { rank: 2, name: 'Priya Sharma', rollNumber: 'CS2024-093', points: 1690, attendance: 92, badge: 'Senior Scholar' },
  { rank: 3, name: 'Alex Mercer', rollNumber: 'CS2024-089', points: 1450, attendance: 84.4, badge: 'Campus Scholar' },
  { rank: 4, name: 'Liam O’Connor', rollNumber: 'CS2024-094', points: 1380, attendance: 81, badge: 'Honor Student' },
  { rank: 5, name: 'Jordan Hayes', rollNumber: 'CS2024-090', points: 1120, attendance: 76, badge: 'Rising Star' },
];

